package exceptionHandling;

public class TryAndCatch {

	public static void main(String[] args)
	{
     int a=10;
     int b=0;
    int c = 0;
  //     System.out.println(c);
     
     try {
		
    	  c=a/b;   //risky code
	   } 
     catch ( ArithmeticException e) 
     {
    	 
    	//System.out.println(e); 
    	System.out.println("we can't divide by zero to any number");
    	
    	 
    }
		System.out.println("ans is "+c);
		
	}

}
